export const countries = [
  {
    key: "none",
    name: "Не указывать",
  },
  {
    key: "US",
    name: "Соединённые Штаты Америки",
    regions: [
      { name: "Алабама", key: "AL" },
      { name: "Аляска", key: "AK" },
      { name: "Калифорния", key: "CA" },
      { name: "Флорида", key: "FL" },
      { name: "Нью-Йорк", key: "NY" },
      { name: "Техас", key: "TX" },
      { name: "Мичиган", key: "MI" },
      { name: "Огайо", key: "OH" },
      { name: "Иллинойс", key: "IL" },
      { name: "Пенсильвания", key: "PA" },
    ],
  },
  {
    key: "UK",
    name: "Великобритания",
    regions: [
      { name: "Англия", key: "ENG" },
      { name: "Шотландия", key: "SCT" },
      { name: "Уэльс", key: "WLS" },
      { name: "Северная Ирландия", key: "NIR" },
      { name: "Большой Лондон", key: "LDN" },
      { name: "Мидлендс", key: "MID" },
      { name: "Южная Англия", key: "SEN" },
      { name: "Северо-Западная Англия", key: "NWE" },
      { name: "Юго-Западная Англия", key: "SWE" },
      { name: "Юго-Восточная Англия", key: "SE" },
    ],
  },
  {
    key: "JP",
    name: "Япония",
    regions: [
      { name: "Хоккайдо", key: "01" },
      { name: "Токио", key: "13" },
      { name: "Осака", key: "27" },
      { name: "Айти", key: "23" },
      { name: "Фукуока", key: "40" },
      { name: "Канагава", key: "14" },
      { name: "Сайтама", key: "11" },
      { name: "Хиого", key: "28" },
      { name: "Сиракава", key: "15" },
      { name: "Киото", key: "26" },
    ],
  },
  {
    key: "RU",
    name: "Россия",
    regions: [
      { name: "Москва", key: "MOW" },
      { name: "Санкт-Петербург", key: "SPE" },
      { name: "Новосибирск", key: "NVS" },
      { name: "Екатеринбург", key: "SVE" },
      { name: "Казань", key: "TA" },
      { name: "Челябинск", key: "CHE" },
      { name: "Нижний Новгород", key: "NGR" },
      { name: "Омск", key: "OMS" },
      { name: "Воронеж", key: "VOR" },
      { name: "Ростов-на-Дону", key: "ROS" },
    ],
  },
  {
    key: "KZ",
    name: "Казахстан",
    regions: [
      { name: "Алматы", key: "ALA" },
      { name: "Нур-Султан", key: "NUR" },
      { name: "Шымкент", key: "SHY" },
      { name: "Караганда", key: "KAR" },
      { name: "Актобе", key: "AKT" },
      { name: "Павлодар", key: "PAV" },
      { name: "Семей", key: "SEM" },
      { name: "Атырау", key: "ATY" },
      { name: "Тараз", key: "TAR" },
      { name: "Костанай", key: "KOS" },
    ],
  },
];
